### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by keszybz**
Assorted cleanups.

### CODE REVIEW

**Comment by wgwoods** [comment]
- 5622f7ad66bfe1e6290dc16c44cb4d75d7745e59: NAK. `dnf.util.clear_dir()` is supposed to empty the named directory (but not delete the directory itself). `shutil.rmtree()` removes the named directory, which isn't what we want here, so it's not a suitable replacement.
- 29a0ddac72636d814912e07c3e800ddf8af7583b: ACK.
- 4888ad408ef3dc0004fac6c8f223c55b4e2615db: ACK.
- b597ea66952e66b691775383058b506e0223d616: NAK. I want to actually fix the cache-smashy bug rather than just printing a "sorry, this is broken!" error message.

**Comment by wgwoods** [comment]
Thanks for the patches - cherry-picked 984609d9e4d55feaf8c5221e93d8a8953aec94e7 and 88447b23d60f433e5448655bc45becbc491e8cb9.

**Comment by keszybz** [comment]
>  is supposed to empty the named directory (but not delete the directory itself)

But why do you need the directory? It has no special access mode and can be recreated at any time...

> I want to actually fix the cache-smashy bug rather than just printing a "sorry, this is broken!" error message.

I'm don't understand this comment. Can you explain?

**Comment by wgwoods** [comment]
> But why do you need the directory? It has no special access mode and can be recreated at any time...

The only place it gets used is during `clean`:

``` python
    def run_clean(self, extcmds):
        if self.state.datadir:
            logger.info(_("Cleaning up downloaded data..."))
            clear_dir(self.state.datadir)
            [etc]
```

`self.state.datadir` is user-configurable, and it might not be a directory we control. (It could very well be something like `/srv` for all we know). We only create it if it's the _default_ datadir:

``` python
        if self.opts.datadir == DEFAULT_DATADIR:
            dnf.util.ensure_dir(self.opts.datadir)
```

So if it's a user-configured directory, they are responsible for creating it (and setting its permissions), and we probably shouldn't delete it.

**Comment by keszybz** [comment]
OK, makes sense.

**Comment by wgwoods** [comment]
> > I want to actually fix the cache-smashy bug rather than just printing a "sorry, this is broken!" error message.
> 
> I'm don't understand this comment. Can you explain?

Sorry, my mistake - _I_ was thinking specifically about the problem where DNF removes cached packages if you run any other DNF command after `download` (like #22, possibly #5, and [rhbz#1276886](https://bugzilla.redhat.com/show_bug.cgi?id=1276886)). But I re-read the message you added:

```
system is not ready for upgrade. This can happen even after 
packages were downloaded when another dnf command installs or
removes packages. Run '%s download --releasever=...' and try again.
```

I _had_ thought this was referring specifically to the cache-smash bug mentioned above, but this message makes sense for the case where the user has added/removed packages after `download`, thus invalidating `State.download_status`.

I'd like to handle that case in the plugin's `transaction()` method (which runs after _any_ successful transaction, according to the [DNF API docs](http://dnf.readthedocs.org/en/latest/api_plugins.html)) so after any other transaction that installs/removes packages we can reset `State.download_status` and tell the user to re-run `dnf system-upgrade download` to refresh the upgrade transaction.

(It might even make sense to add a `--retry` or `--resume` flag¹ as a shortcut, so the user doesn't have to remember which combination of `--releasever=XXX --best --allowerasing --exclude=XXX` etc. they used.)

¹ not `--refresh` though - that's already taken by DNF.

**Pull request closed without merging**
