### PR TITLE
fedup: make fedup.sh a simple pass-through for the plugin

### PR DESCRIPTION
**Pull request by keszybz**
All the option parsing is moved to the ArgumentParser of the plugin.
Things should mostly stay the same, but some minor differences are
bound to happen.

Intentional differences:
- error strings were changed to always include the offending option
  name
- --test-gettext is gone
#15

### CODE REVIEW

**Comment by wgwoods** [comment]
Love it - one minor problem:

``` python-traceback
ImportError: Failed to import test module: test_system_upgrade
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib64/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/wwoods/src/dnf-plugin-system-upgrade/tests/test_system_upgrade.py", line 3, in <module>
    import system_upgrade
  File "system_upgrade.py", line 248
SyntaxError: Non-ASCII character '\xe2' in file system_upgrade.py on line 248, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

(Also lines 258 and 262 - it's the the em-dash characters in those comments, I guess)

Just to double-check - does this patch handle _all_ the options that `fedup.sh` was parsing? It looks like it does but I'm having a little trouble confirming it manually. Once I've confirmed that, I'll be happy to merge this. And thanks very much for the patch!

**Comment by keszybz** [comment]
I got lazy and didn't test under Python 2. I'll prepare an updated version.

> Just to double-check - does this patch handle all the options that fedup.sh was parsing?

Yes, apart from --test-gettext.

**Comment by keszybz** [comment]
M-dashes are now changed to normal dashes.

**Comment by wgwoods** [comment]
Awesome. I love patches that remove more code than they add, _especially_ when they remove shell scripts. Bless you, sir. I owe you a beer or something.

**Pull request merged**
