### PR TITLE
disable screen blanking

### PR DESCRIPTION
**Pull request by kparal**
This should solve #26 and obsolete #28. Kudos to Zbigniew
Jędrzejewski-Szmek.

It seems to work for me, but additional testing would be welcome.

### CODE REVIEW

**Comment by keszybz** [comment]
Looks OK. 'return' is not needed though.

**Comment by kparal** [comment]
Amended.

**Comment by kparal** [comment]
Hello? We still see screen blanking when doing tests for F24. @wgwoods Can we please include this and build a new release? Thanks.

**Comment by j-mracek** [comment]
I am really sorry for too late response. The project was moved into dnf-plugins-extras. Please if you think that issue is still relevant in Fedora 27+, please create a new PR or issue.

**Comment by kparal** [comment]
I tested with `dnf-2.7.5-12.fc28.noarch` and I haven't seen any blanking (plymouth switched to text mode by an arrow; booted without rhgb; plymouth uninstalled). So it seems this PR is no longer needed.

**Pull request closed without merging**
